//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.01 at 06:15:36 PM IST 
//


package com.quantiguous.iib.tools.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatabaseMetaDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatabaseMetaDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="databaseMajorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="databaseMinorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="driverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="driverVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jdbcMajorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="jdbcMinorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="databaseURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="schemas" type="{http://www.quantiguous.com/tools}databaseSchemasType"/>
 *         &lt;element name="catalogs" type="{http://www.quantiguous.com/tools}databaseCatalogsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatabaseMetaDataType", propOrder = {
    "productName",
    "productVersion",
    "databaseMajorVersion",
    "databaseMinorVersion",
    "driverName",
    "driverVersion",
    "jdbcMajorVersion",
    "jdbcMinorVersion",
    "databaseURL",
    "userName",
    "schema",
    "schemas",
    "catalogs"
})
public class DatabaseMetaDataType {

    @XmlElement(required = true)
    protected String productName;
    @XmlElement(required = true)
    protected String productVersion;
    protected int databaseMajorVersion;
    protected int databaseMinorVersion;
    @XmlElement(required = true)
    protected String driverName;
    @XmlElement(required = true)
    protected String driverVersion;
    protected int jdbcMajorVersion;
    protected int jdbcMinorVersion;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String databaseURL;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected String schema;
    @XmlElement(required = true)
    protected DatabaseSchemasType schemas;
    @XmlElement(required = true)
    protected DatabaseCatalogsType catalogs;

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductVersion() {
        return productVersion;
    }

    /**
     * Sets the value of the productVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductVersion(String value) {
        this.productVersion = value;
    }

    /**
     * Gets the value of the databaseMajorVersion property.
     * 
     */
    public int getDatabaseMajorVersion() {
        return databaseMajorVersion;
    }

    /**
     * Sets the value of the databaseMajorVersion property.
     * 
     */
    public void setDatabaseMajorVersion(int value) {
        this.databaseMajorVersion = value;
    }

    /**
     * Gets the value of the databaseMinorVersion property.
     * 
     */
    public int getDatabaseMinorVersion() {
        return databaseMinorVersion;
    }

    /**
     * Sets the value of the databaseMinorVersion property.
     * 
     */
    public void setDatabaseMinorVersion(int value) {
        this.databaseMinorVersion = value;
    }

    /**
     * Gets the value of the driverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * Sets the value of the driverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverName(String value) {
        this.driverName = value;
    }

    /**
     * Gets the value of the driverVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverVersion() {
        return driverVersion;
    }

    /**
     * Sets the value of the driverVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverVersion(String value) {
        this.driverVersion = value;
    }

    /**
     * Gets the value of the jdbcMajorVersion property.
     * 
     */
    public int getJdbcMajorVersion() {
        return jdbcMajorVersion;
    }

    /**
     * Sets the value of the jdbcMajorVersion property.
     * 
     */
    public void setJdbcMajorVersion(int value) {
        this.jdbcMajorVersion = value;
    }

    /**
     * Gets the value of the jdbcMinorVersion property.
     * 
     */
    public int getJdbcMinorVersion() {
        return jdbcMinorVersion;
    }

    /**
     * Sets the value of the jdbcMinorVersion property.
     * 
     */
    public void setJdbcMinorVersion(int value) {
        this.jdbcMinorVersion = value;
    }

    /**
     * Gets the value of the databaseURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseURL() {
        return databaseURL;
    }

    /**
     * Sets the value of the databaseURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseURL(String value) {
        this.databaseURL = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchema(String value) {
        this.schema = value;
    }

    /**
     * Gets the value of the schemas property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseSchemasType }
     *     
     */
    public DatabaseSchemasType getSchemas() {
        return schemas;
    }

    /**
     * Sets the value of the schemas property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseSchemasType }
     *     
     */
    public void setSchemas(DatabaseSchemasType value) {
        this.schemas = value;
    }

    /**
     * Gets the value of the catalogs property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseCatalogsType }
     *     
     */
    public DatabaseCatalogsType getCatalogs() {
        return catalogs;
    }

    /**
     * Sets the value of the catalogs property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseCatalogsType }
     *     
     */
    public void setCatalogs(DatabaseCatalogsType value) {
        this.catalogs = value;
    }

}
