//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.01 at 06:15:36 PM IST 
//


package com.quantiguous.iib.tools.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JdbcProviderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JdbcProviderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="connectionUrlFormat" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="databaseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="databaseSchemaNames" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="databaseType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="databaseVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="environmentParms" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jarsURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maxConnectionPoolSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="portNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="securityIdentity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="testResults" type="{http://www.quantiguous.com/tools}testResultsType"/>
 *         &lt;element name="metaData" type="{http://www.quantiguous.com/tools}DatabaseMetaDataType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JdbcProviderType", propOrder = {

})
public class JdbcProviderType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String connectionUrlFormat;
    @XmlElement(required = true)
    protected String databaseName;
    @XmlElement(required = true)
    protected String databaseSchemaNames;
    @XmlElement(required = true)
    protected String databaseType;
    @XmlElement(required = true)
    protected String databaseVersion;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String environmentParms;
    @XmlElement(required = true)
    protected String jarsURL;
    @XmlElement(required = true)
    protected String maxConnectionPoolSize;
    @XmlElement(required = true)
    protected String portNumber;
    @XmlElement(required = true)
    protected String securityIdentity;
    @XmlElement(required = true)
    protected String serverName;
    @XmlElement(required = true)
    protected TestResultsType testResults;
    @XmlElement(required = true)
    protected DatabaseMetaDataType metaData;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the connectionUrlFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionUrlFormat() {
        return connectionUrlFormat;
    }

    /**
     * Sets the value of the connectionUrlFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionUrlFormat(String value) {
        this.connectionUrlFormat = value;
    }

    /**
     * Gets the value of the databaseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseName() {
        return databaseName;
    }

    /**
     * Sets the value of the databaseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseName(String value) {
        this.databaseName = value;
    }

    /**
     * Gets the value of the databaseSchemaNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseSchemaNames() {
        return databaseSchemaNames;
    }

    /**
     * Sets the value of the databaseSchemaNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseSchemaNames(String value) {
        this.databaseSchemaNames = value;
    }

    /**
     * Gets the value of the databaseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseType() {
        return databaseType;
    }

    /**
     * Sets the value of the databaseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseType(String value) {
        this.databaseType = value;
    }

    /**
     * Gets the value of the databaseVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseVersion() {
        return databaseVersion;
    }

    /**
     * Sets the value of the databaseVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseVersion(String value) {
        this.databaseVersion = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the environmentParms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironmentParms() {
        return environmentParms;
    }

    /**
     * Sets the value of the environmentParms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironmentParms(String value) {
        this.environmentParms = value;
    }

    /**
     * Gets the value of the jarsURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJarsURL() {
        return jarsURL;
    }

    /**
     * Sets the value of the jarsURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJarsURL(String value) {
        this.jarsURL = value;
    }

    /**
     * Gets the value of the maxConnectionPoolSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxConnectionPoolSize() {
        return maxConnectionPoolSize;
    }

    /**
     * Sets the value of the maxConnectionPoolSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxConnectionPoolSize(String value) {
        this.maxConnectionPoolSize = value;
    }

    /**
     * Gets the value of the portNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortNumber() {
        return portNumber;
    }

    /**
     * Sets the value of the portNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortNumber(String value) {
        this.portNumber = value;
    }

    /**
     * Gets the value of the securityIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityIdentity() {
        return securityIdentity;
    }

    /**
     * Sets the value of the securityIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityIdentity(String value) {
        this.securityIdentity = value;
    }

    /**
     * Gets the value of the serverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * Sets the value of the serverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerName(String value) {
        this.serverName = value;
    }

    /**
     * Gets the value of the testResults property.
     * 
     * @return
     *     possible object is
     *     {@link TestResultsType }
     *     
     */
    public TestResultsType getTestResults() {
        return testResults;
    }

    /**
     * Sets the value of the testResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestResultsType }
     *     
     */
    public void setTestResults(TestResultsType value) {
        this.testResults = value;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseMetaDataType }
     *     
     */
    public DatabaseMetaDataType getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseMetaDataType }
     *     
     */
    public void setMetaData(DatabaseMetaDataType value) {
        this.metaData = value;
    }

}
