//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.01 at 06:15:36 PM IST 
//


package com.quantiguous.iib.tools.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="testName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="testSuccessful" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="testResult" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="testException" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testResultType", propOrder = {

})
public class TestResultType {

    @XmlElement(required = true)
    protected String testName;
    protected boolean testSuccessful;
    @XmlElement(required = true)
    protected String testResult;
    @XmlElement(required = true)
    protected String testException;

    /**
     * Gets the value of the testName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestName() {
        return testName;
    }

    /**
     * Sets the value of the testName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestName(String value) {
        this.testName = value;
    }

    /**
     * Gets the value of the testSuccessful property.
     * 
     */
    public boolean isTestSuccessful() {
        return testSuccessful;
    }

    /**
     * Sets the value of the testSuccessful property.
     * 
     */
    public void setTestSuccessful(boolean value) {
        this.testSuccessful = value;
    }

    /**
     * Gets the value of the testResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * Sets the value of the testResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestResult(String value) {
        this.testResult = value;
    }

    /**
     * Gets the value of the testException property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestException() {
        return testException;
    }

    /**
     * Sets the value of the testException property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestException(String value) {
        this.testException = value;
    }

}
